
import React, { useRef, useState } from 'react';
import { DownloadIcon } from './icons/DownloadIcon';
import LatexRenderer from './LatexRenderer';
import { generateNotesDocx } from '../utils/exportUtils';
import { downloadPdf } from '../utils/downloadUtils';
import { Spinner } from './Spinner';
import type { UserInputs } from '../types';

interface NotesProps {
  notes: string;
  title: string;
  inputs?: UserInputs;
}

// Printable component for PDF generation with a professional layout
const PrintableNotes: React.FC<{ notes: string, title: string, inputs?: UserInputs }> = ({ notes, title, inputs }) => {
  const date = new Date().toLocaleDateString();
  const subject = inputs?.subject || "Subject";
  const grade = inputs?.grade || "Grade";
  const standard = inputs?.standard ? `(${inputs.standard})` : "";

  return (
    <div 
      className="bg-white text-black font-serif"
      style={{ 
        width: '800px', 
        padding: '50px', 
        fontSize: '11pt',
        lineHeight: '1.6',
        color: '#1f2937' // slate-800
      }}
    >
      {/* Professional Header */}
      <header className="mb-8 border-b-2 border-black pb-4 print-item">
        <div className="flex justify-between items-end mb-4 font-sans">
          <div className="text-left">
             <h2 className="text-lg font-bold text-gray-900 uppercase tracking-wider">{subject}</h2>
             <p className="text-sm text-gray-600 font-medium">{grade} {standard}</p>
          </div>
          <div className="text-right">
            <p className="text-sm text-gray-600 font-medium">Date: {date}</p>
            <p className="text-sm text-gray-600 font-medium uppercase tracking-wide">Study Notes</p>
          </div>
        </div>
        <h1 className="text-center font-sans font-extrabold text-3xl text-black mt-2 leading-tight">
          {title}
        </h1>
      </header>

      {/* Content Body */}
      <div className="notes-content text-justify space-y-4">
        <LatexRenderer content={notes} enableMarkdown={true} />
      </div>

      {/* Footer */}
      <footer className="mt-12 pt-4 border-t border-gray-300 flex justify-between text-xs text-gray-400 font-sans print-item">
        <span>Generated by LessonLab</span>
        <span>Page 1</span>
      </footer>
    </div>
  );
};

const Notes: React.FC<NotesProps> = ({ notes, title, inputs }) => {
  const printableNotesRef = useRef<HTMLDivElement>(null);
  const [isDownloading, setIsDownloading] = useState<string | null>(null);

  const handleDownloadPdf = async () => {
    if (!printableNotesRef.current) return;
    setIsDownloading('pdf');

    try {
        await downloadPdf({
            filename: `${title.replace(/\s+/g, '_')}-notes.pdf`,
            element: printableNotesRef.current,
            orientation: 'p',
            margin: 40
        });
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsDownloading(null);
    }
  };

  const handleDownloadDocx = async () => {
    setIsDownloading('docx');
    try {
      await generateNotesDocx(notes, title);
    } catch (error) {
      console.error("Error generating DOCX:", error);
      alert("Failed to generate Word document. Please try again.");
    } finally {
      setIsDownloading(null);
    }
  };

  return (
    <>
      <div className="absolute top-[-9999px] left-[-9999px]">
        <div ref={printableNotesRef}>
          <PrintableNotes notes={notes} title={title} inputs={inputs} />
        </div>
      </div>

      <div className="space-y-6">
        <div className="flex flex-col sm:flex-row justify-between sm:items-center gap-4 border-b-2 border-sky-200 pb-2">
          <h2 className="text-3xl font-bold text-slate-800">Student Notes</h2>
           <div className="flex items-center gap-2 flex-wrap">
              <button
                onClick={handleDownloadDocx}
                disabled={!!isDownloading}
                className="inline-flex items-center px-4 py-2 bg-blue-100 text-blue-700 text-sm font-semibold rounded-lg shadow-sm hover:bg-blue-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                aria-label="Download notes as a Word document"
              >
                <div className="h-5 w-5 mr-2">
                  {isDownloading === 'docx' ? (
                    <Spinner className="h-full w-full" />
                  ) : (
                    <DownloadIcon />
                  )}
                </div>
                {isDownloading === 'docx' ? 'Generating...' : 'Download Word'}
              </button>
              <button
                onClick={handleDownloadPdf}
                disabled={!!isDownloading}
                className="inline-flex items-center px-4 py-2 bg-slate-100 text-slate-700 text-sm font-semibold rounded-lg shadow-sm hover:bg-slate-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                aria-label="Download notes as PDF"
              >
                <div className="h-5 w-5 mr-2">
                  {isDownloading === 'pdf' ? (
                    <Spinner className="h-full w-full" />
                  ) : (
                    <DownloadIcon />
                  )}
                </div>
                {isDownloading === 'pdf' ? 'Generating...' : 'Download PDF'}
              </button>
            </div>
        </div>

        <div className="bg-slate-50 p-8 rounded-lg border border-slate-200 shadow-sm">
             <div className="prose prose-slate max-w-none">
                 <LatexRenderer content={notes} className="text-slate-700 whitespace-pre-wrap" enableMarkdown={true} />
             </div>
        </div>
      </div>
    </>
  );
};

export default Notes;
