import katex from 'katex';

/**
 * Takes a string containing potential LaTeX expressions and pre-renders them to HTML using KaTeX.
 * If rendering fails, it wraps the original LaTeX in a styled `<code>` tag for clear feedback.
 * @param content The input string which may contain LaTeX and other HTML.
 * @returns An HTML string with all LaTeX expressions converted to KaTeX's HTML markup or styled as an error.
 */
export const preRenderLatex = (content: string): string => {
  if (!content) return '';
  
  // This regex finds block `\[...\]` expressions and inline `\(...\)` expressions.
  // It uses simple non-greedy matching. The callback then validates the content.
  return content.replace(/\\\[(.*?)\\\]|\\\((.*?)\\\)/gs, (match, blockContent, inlineContent) => {
    const isBlock = blockContent !== undefined;
    const latex = isBlock ? blockContent : inlineContent;

    if (latex === undefined) return match;
    
    // Gracefully handle malformed nesting: inline math `\(...\)` containing block math `\[...\]`
    if (!isBlock && (latex.includes('\\\[') || latex.includes('\\\\]'))) {
      console.error("KaTeX pre-rendering skipped for malformed nesting:", `"${latex.trim()}"`);
      const style = "background-color: #fee2e2; color: #b91c1c; font-family: monospace; padding: 2px 4px; border-radius: 4px; display: inline-block;";
      const title = `KaTeX Error: Found block delimiters \\[\\] inside an inline expression \\(\\)`;
      return `<code style="${style}" title="${title}">${match}</code>`;
    }

    try {
      // FIX: Added replacement for form-feed characters (\f) which can be erroneously
      // generated by the model and cause KaTeX parsing to fail.
      const cleanedLatex = latex.trim().replace(/\f/g, '');
      // Use katex.renderToString to convert the LaTeX string directly into an HTML string.
      // Throw an error on failure so we can catch it and provide a graceful fallback.
      return katex.renderToString(cleanedLatex, {
        displayMode: isBlock,
        throwOnError: true,
      });
    } catch (e: any) {
      console.error("KaTeX pre-rendering failed for:", `"${latex.trim()}"`, e);
      // Fallback: Display the raw LaTeX code in a styled way.
      // This is less disruptive than a big red error message and helps identify the faulty LaTeX.
      const style = "background-color: #fee2e2; color: #b91c1c; font-family: monospace; padding: 2px 4px; border-radius: 4px; display: inline-block;";
      const title = `KaTeX Error: ${e.message.replace(/"/g, '&quot;')}`;
      return `<code style="${style}" title="${title}">${match}</code>`;
    }
  });
};